root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/file-hosting.exe ./cmd/file-hosting"
  entrypoint = ["./tmp/file-hosting.exe"]
  include_ext = ["go"]
  exclude_dir = ["tmp", "files"]
  stop_on_error = true

[log]
  time = true
